# Generated by Django 5.2.17 on 2026-09-15 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='规则代码')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='说明')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('severity', models.CharField(choices=[('info', '提示'), ('warning', '警告'), ('critical', '严重')], default='warning', max_length=16, verbose_name='级别')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='参数')),
            ],
            options={
                'verbose_name': '预警规则',
                'verbose_name_plural': '预警规则',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dedup_key', models.CharField(max_length=200, verbose_name='去重键')),
                ('object_id', models.PositiveBigIntegerField()),
                ('severity', models.CharField(choices=[('info', '提示'), ('warning', '警告'), ('critical', '严重')], max_length=16, verbose_name='级别')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('message', models.TextField(blank=True, verbose_name='说明')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='链接')),
                ('status', models.CharField(choices=[('open', '待处理'), ('ack', '已知悉'), ('resolved', '已解除')], default='open', max_length=16, verbose_name='状态')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='首次触发')),
                ('last_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='最近触发')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='知悉时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解除时间')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='知悉人')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='alerts.alertrule', verbose_name='规则')),
            ],
            options={
                'verbose_name': '预警',
                'verbose_name_plural': '预警',
                'ordering': ['-first_seen_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='alerts_aler_content_a9e91b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'resolved'), _negated=True), fields=('dedup_key',), name='uniq_active_alert_key')],
            },
        ),
    ]
