line-length = 110
target-version = "py312"
extend-exclude = ["**/migrations/**", "docs/**"]

[lint]
select = ["E", "F", "I", "B", "UP"]

[lint.per-file-ignores]
"config/settings/*.py" = ["F403", "F405"]
