# Generated by Django 5.2.17 on 2026-09-15 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=32, verbose_name='外部系统')),
                ('entity', models.CharField(max_length=64, verbose_name='数据类型')),
                ('direction', models.CharField(choices=[('pull', '拉取'), ('push', '推送')], max_length=8, verbose_name='方向')),
                ('status', models.CharField(choices=[('pending', '排队中'), ('running', '执行中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=16, verbose_name='状态')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='参数')),
                ('stats', models.JSONField(blank=True, default=dict, verbose_name='统计')),
                ('error', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='触发人')),
            ],
            options={
                'verbose_name': '同步任务',
                'verbose_name_plural': '同步任务',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExternalRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('system', models.CharField(max_length=32, verbose_name='外部系统')),
                ('external_id', models.CharField(max_length=64, verbose_name='外部 ID')),
                ('external_number', models.CharField(blank=True, max_length=64, verbose_name='外部编号')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='最近同步')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': '外部 ID 映射',
                'verbose_name_plural': '外部 ID 映射',
                'constraints': [models.UniqueConstraint(fields=('system', 'content_type', 'external_id'), name='uniq_extref_external'), models.UniqueConstraint(fields=('system', 'content_type', 'object_id'), name='uniq_extref_local')],
            },
        ),
    ]
