# Generated by Django 5.2.17 on 2026-09-15 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchasing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ship_date', models.DateField(verbose_name='出货日期')),
                ('forwarder', models.CharField(blank=True, max_length=100, verbose_name='货代')),
                ('tracking_no', models.CharField(blank=True, max_length=64, verbose_name='提单号 / 运单号')),
                ('container_no', models.CharField(blank=True, max_length=32, verbose_name='柜号')),
                ('eta', models.DateField(blank=True, null=True, verbose_name='预计到港')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='purchasing.purchaseorder', verbose_name='采购单')),
            ],
            options={
                'verbose_name': '出货记录',
                'verbose_name_plural': '出货记录',
                'ordering': ['-ship_date', '-id'],
            },
        ),
    ]
