# Generated by Django 5.2.17 on 2026-09-15 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='客户编码')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('currency', models.CharField(default='JPY', max_length=3, verbose_name='结算币种')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='供应商编码')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('contact_name', models.CharField(blank=True, max_length=64, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('lead_time_days', models.PositiveIntegerField(default=30, verbose_name='标准生产周期（天）')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('part_no', models.CharField(max_length=64, unique=True, verbose_name='品番')),
                ('name', models.CharField(max_length=200, verbose_name='品名')),
                ('name_ja', models.CharField(blank=True, max_length=200, verbose_name='日文品名')),
                ('jan_code', models.CharField(blank=True, max_length=13, verbose_name='JAN 码')),
                ('carton_qty', models.PositiveIntegerField(default=1, verbose_name='箱入数')),
                ('status', models.CharField(choices=[('active', '在售'), ('discontinued', '废番')], default='active', max_length=16, verbose_name='状态')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
                ('default_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='masterdata.supplier', verbose_name='默认供应商')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['part_no'],
            },
        ),
    ]
