# Generated by Django 5.2.17 on 2026-09-15 15:58

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPurchaseOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新时间')),
                ('number', models.CharField(db_index=True, editable=False, max_length=32, verbose_name='采购单号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_confirm', '待供应商确认'), ('in_production', '生产中'), ('pending_inspection', '待验货'), ('ready_to_ship', '待出货'), ('shipped', '已出货'), ('cancelled', '已取消')], db_index=True, default='draft', max_length=24, verbose_name='状态')),
                ('order_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='下单日期')),
                ('required_date', models.DateField(verbose_name='要求交期')),
                ('promised_date', models.DateField(blank=True, null=True, verbose_name='承诺交期')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='出货时间')),
                ('reject_reason', models.CharField(blank=True, max_length=255, verbose_name='供应商拒绝原因')),
                ('note', models.TextField(blank=True, verbose_name='给供应商的备注')),
                ('internal_note', models.TextField(blank=True, verbose_name='内部备注')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.customer', verbose_name='客户')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='跟单员')),
                ('supplier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': 'historical 采购单',
                'verbose_name_plural': 'historical 采购单',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('number', models.CharField(editable=False, max_length=32, unique=True, verbose_name='采购单号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_confirm', '待供应商确认'), ('in_production', '生产中'), ('pending_inspection', '待验货'), ('ready_to_ship', '待出货'), ('shipped', '已出货'), ('cancelled', '已取消')], db_index=True, default='draft', max_length=24, verbose_name='状态')),
                ('order_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='下单日期')),
                ('required_date', models.DateField(verbose_name='要求交期')),
                ('promised_date', models.DateField(blank=True, null=True, verbose_name='承诺交期')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='出货时间')),
                ('reject_reason', models.CharField(blank=True, max_length=255, verbose_name='供应商拒绝原因')),
                ('note', models.TextField(blank=True, verbose_name='给供应商的备注')),
                ('internal_note', models.TextField(blank=True, verbose_name='内部备注')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='masterdata.customer', verbose_name='客户')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='跟单员')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='masterdata.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '采购单',
                'verbose_name_plural': '采购单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryDateChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_date', models.DateField(blank=True, null=True, verbose_name='原交期')),
                ('new_date', models.DateField(verbose_name='新交期')),
                ('reason', models.CharField(max_length=255, verbose_name='原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='变更人')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_changes', to='purchasing.purchaseorder')),
            ],
            options={
                'verbose_name': '交期变更',
                'verbose_name_plural': '交期变更',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='数量')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='单价')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.purchaseorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_lines', to='masterdata.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '采购明细',
                'verbose_name_plural': '采购明细',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('material', '备料完成'), ('start', '开工'), ('done', '完工'), ('inspection', '验货')], max_length=16, verbose_name='节点')),
                ('seq', models.PositiveSmallIntegerField(default=0)),
                ('planned_date', models.DateField(blank=True, null=True, verbose_name='计划日期')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='实际日期')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='purchasing.purchaseorder')),
            ],
            options={
                'verbose_name': '生产节点',
                'verbose_name_plural': '生产节点',
                'ordering': ['seq'],
                'constraints': [models.UniqueConstraint(fields=('po', 'kind'), name='uniq_po_milestone_kind')],
            },
        ),
    ]
